version: '2'
services:
  fosterleads-app:
    image: fosterleads
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://fosterleads-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=FosterLeads
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  fosterleads-mongodb:
    extends:
      file: mongodb.yml
      service: fosterleads-mongodb
